services:
  tortuga:
    image: lscr.io/linuxserver/jellyfin
    container_name: tortuga
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MEDIA_ROOT}/config/jellyfin:/config
      - ${MEDIA_ROOT}/movies:/media/movies
    networks: [edge]
    restart: unless-stopped

  blackpearl:
    image: lscr.io/linuxserver/qbittorrent
    container_name: blackpearl
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - ${MEDIA_ROOT}/config/qbittorrent:/config
      - ${MEDIA_ROOT}/downloads:/downloads
    networks: [edge]
    restart: unless-stopped

networks:
  edge:
    external: true
    name: ${DOCKER_NETWORK}
